"""Pick/reject flags, export history, custom tags, captions and fixed tags: the
user-created data.

Stored in their own SQLite file, outside ``data_dir``, keyed by file content
(sha256). Deleting the derived data and re-indexing, or moving files, keeps them;
editing a file (new content) drops them. Unflagged photos have no flags row;
photos never exported have no exported row. Flag and exported are independent.
"""

from __future__ import annotations

import sqlite3
import time
from pathlib import Path

FLAGS = ("pick", "reject")
VERSION = 9  # PRAGMA user_version: the tables in SCHEMA are created when missing

SCHEMA = """
CREATE TABLE IF NOT EXISTS flags (
  sha256     TEXT PRIMARY KEY,
  flag       TEXT NOT NULL CHECK (flag IN ('pick', 'reject')),
  source     TEXT,              -- last known location, for humans and recovery
  rel_path   TEXT,
  updated_at REAL NOT NULL
);

-- v2: which photos have been exported (independent of the flag).
CREATE TABLE IF NOT EXISTS exported (
  sha256      TEXT PRIMARY KEY,
  first_at    REAL NOT NULL,
  last_at     REAL NOT NULL,
  times       INTEGER NOT NULL DEFAULT 1,
  last_folder TEXT,             -- where the last export went
  source      TEXT,             -- last known location, for humans and recovery
  rel_path    TEXT
);

-- v3: tags taught by example photos (custom_tags.py).
CREATE TABLE IF NOT EXISTS custom_tags (
  id          INTEGER PRIMARY KEY,
  name        TEXT NOT NULL UNIQUE COLLATE NOCASE,
  strictness  TEXT NOT NULL DEFAULT 'normal' CHECK (strictness IN ('strict', 'normal', 'loose')),
  created_at  REAL NOT NULL,
  updated_at  REAL NOT NULL
);
CREATE TABLE IF NOT EXISTS custom_tag_examples (
  tag_id      INTEGER NOT NULL REFERENCES custom_tags(id),
  sha256      TEXT NOT NULL,
  source      TEXT,             -- last known location, for humans and recovery
  rel_path    TEXT,
  added_at    REAL NOT NULL,
  PRIMARY KEY (tag_id, sha256)
);

-- v7: photos marked as not belonging to a custom tag (custom_tags.py): a photo
-- closer to one of these than to every example is left out.
CREATE TABLE IF NOT EXISTS custom_tag_negatives (
  tag_id      INTEGER NOT NULL REFERENCES custom_tags(id),
  sha256      TEXT NOT NULL,
  source      TEXT,
  rel_path    TEXT,
  added_at    REAL NOT NULL,
  PRIMARY KEY (tag_id, sha256)
);

-- v8: this profile's photo folders (profiles.folders; the default profile keeps
-- them in config.yaml). profile_settings 'folders' = '1' once the list was set, so
-- a profile from before v8 starts with the config's folders instead of none.
CREATE TABLE IF NOT EXISTS folders (
  path        TEXT PRIMARY KEY,
  added_at    REAL NOT NULL
);
CREATE TABLE IF NOT EXISTS profile_settings (
  key         TEXT PRIMARY KEY,
  value       TEXT
);

-- v4: this file's profile name (profiles.py); empty in the default profile.
CREATE TABLE IF NOT EXISTS profile (
  name TEXT NOT NULL
);

-- v5: written captions and fixed tags (typed, or generated by captioning.py).
-- method: manual, riffle, phrases, joycaption, wd. edited: the caption was changed
-- by hand, so generating again keeps it unless told to replace everything.
CREATE TABLE IF NOT EXISTS captions (
  sha256     TEXT PRIMARY KEY,
  text       TEXT NOT NULL,
  method     TEXT,
  edited     INTEGER NOT NULL DEFAULT 0,
  source     TEXT,              -- last known location, for humans and recovery
  rel_path   TEXT,
  updated_at REAL NOT NULL
);
CREATE TABLE IF NOT EXISTS fixed_tags (
  sha256   TEXT NOT NULL,
  tag      TEXT NOT NULL COLLATE NOCASE,
  position INTEGER NOT NULL,    -- order within the photo (training files keep it)
  method   TEXT,
  source   TEXT,
  rel_path TEXT,
  added_at REAL NOT NULL,
  PRIMARY KEY (sha256, tag)
);
CREATE INDEX IF NOT EXISTS fixed_tags_tag ON fixed_tags(tag);

-- v6: text read from the photo (OCR) and its English translation. text '' means
-- read, no text found (so filling gaps does not read it again).
CREATE TABLE IF NOT EXISTS photo_text (
  sha256      TEXT PRIMARY KEY,
  text        TEXT NOT NULL,
  translation TEXT NOT NULL DEFAULT '',
  language    TEXT,
  method      TEXT,
  edited      INTEGER NOT NULL DEFAULT 0,
  source      TEXT,
  rel_path    TEXT,
  updated_at  REAL NOT NULL
);
"""

STRICTNESS = ("strict", "normal", "loose")

def flag_expr(alias: str = "p") -> str:
    """SQL for a photo's flag ('pick', 'reject' or NULL), for catalogue connections
    that attached the selections DB as "sel" (see db.connect / db.connect_readonly)."""
    return f"(SELECT fl.flag FROM sel.flags fl WHERE fl.sha256 = {alias}.sha256)"


FLAG_EXPR = flag_expr("p")


def exported_expr(alias: str = "p") -> str:
    """SQL: 1 if the photo was exported before, else 0 (needs "sel" attached)."""
    return f"EXISTS (SELECT 1 FROM sel.exported ex WHERE ex.sha256 = {alias}.sha256)"


EXPORTED_EXPR = exported_expr("p")


def connect(path: str | Path) -> sqlite3.Connection:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(path, check_same_thread=False)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode = WAL")
    conn.executescript(SCHEMA)
    # v9: a custom tag's cut (custom_tags.py: how like its examples a photo must be; NULL:
    # its strictness preset). A column, so a profile copy (INSERT … SELECT *) keeps it.
    if "cut" not in {r[1] for r in conn.execute("PRAGMA table_info(custom_tags)")}:
        conn.execute("ALTER TABLE custom_tags ADD COLUMN cut REAL")
    conn.execute(f"PRAGMA user_version = {VERSION}")
    conn.commit()
    return conn


def ensure(path: str | Path) -> None:
    """Create the selections DB if missing, so read-only attaches work."""
    connect(path).close()


def set_flags(
    catalogue: sqlite3.Connection, path: str | Path, ops: list[tuple[list[int], str | None]]
) -> dict[int, str | None]:
    """Apply ``[(photo ids, flag or None)]`` atomically, in order.

    Returns each photo's flag from before the change (for undo). Unknown ids
    are ignored."""
    ids = sorted({i for photo_ids, _ in ops for i in photo_ids})
    if not ids:
        return {}
    marks = ",".join("?" * len(ids))
    photos = {
        r["id"]: r
        for r in catalogue.execute(
            f"SELECT id, sha256, source, rel_path FROM photos WHERE id IN ({marks}) AND sha256 != ''",
            ids,
        )
    }
    if not photos:
        return {}
    conn = connect(path)
    try:
        shas = sorted({r["sha256"] for r in photos.values()})
        smarks = ",".join("?" * len(shas))
        current = dict(
            conn.execute(f"SELECT sha256, flag FROM flags WHERE sha256 IN ({smarks})", shas).fetchall()
        )
        previous = {pid: current.get(r["sha256"]) for pid, r in photos.items()}
        now = time.time()
        with conn:
            for photo_ids, flag in ops:
                if flag is not None and flag not in FLAGS:
                    raise ValueError(f"flag must be one of {FLAGS} or null")
                for pid in photo_ids:
                    r = photos.get(pid)
                    if r is None:
                        continue
                    if flag is None:
                        conn.execute("DELETE FROM flags WHERE sha256 = ?", (r["sha256"],))
                    else:
                        conn.execute(
                            """INSERT INTO flags (sha256, flag, source, rel_path, updated_at)
                               VALUES (?, ?, ?, ?, ?)
                               ON CONFLICT (sha256) DO UPDATE SET flag = excluded.flag,
                                 source = excluded.source, rel_path = excluded.rel_path,
                                 updated_at = excluded.updated_at""",
                            (r["sha256"], flag, r["source"], r["rel_path"], now),
                        )
        return previous
    finally:
        conn.close()


def clear_flags(
    catalogue: sqlite3.Connection, path: str | Path, photo_ids: list[int] | None = None
) -> dict[int, str]:
    """Unflag the given photos, or everything (including flags of files no longer
    in the library) when ``photo_ids`` is None. Returns the previous flags of the
    affected catalogue photos, for undo."""
    conn = connect(path)
    try:
        flags = dict(conn.execute("SELECT sha256, flag FROM flags").fetchall())
        rows = catalogue.execute("SELECT id, sha256 FROM photos WHERE sha256 != ''").fetchall()
        if photo_ids is not None:
            wanted = set(photo_ids)
            rows = [r for r in rows if r["id"] in wanted]
        previous = {r["id"]: flags[r["sha256"]] for r in rows if r["sha256"] in flags}
        with conn:
            if photo_ids is None:
                conn.execute("DELETE FROM flags")
            else:
                conn.executemany(
                    "DELETE FROM flags WHERE sha256 = ?", [(r["sha256"],) for r in rows]
                )
        return previous
    finally:
        conn.close()


def _photos(catalogue: sqlite3.Connection, photo_ids: list[int] | None):
    rows = catalogue.execute("SELECT id, sha256, source, rel_path FROM photos WHERE sha256 != ''").fetchall()
    if photo_ids is not None:
        wanted = set(photo_ids)
        rows = [r for r in rows if r["id"] in wanted]
    return rows


def mark_exported(catalogue: sqlite3.Connection, path: str | Path, photo_ids: list[int], folder: str) -> int:
    """Record that these photos were exported (to ``folder``). Returns how many."""
    rows = _photos(catalogue, photo_ids)
    now = time.time()
    conn = connect(path)
    try:
        with conn:
            conn.executemany(
                """INSERT INTO exported (sha256, first_at, last_at, times, last_folder, source, rel_path)
                   VALUES (?, ?, ?, 1, ?, ?, ?)
                   ON CONFLICT (sha256) DO UPDATE SET last_at = excluded.last_at,
                     times = exported.times + 1, last_folder = excluded.last_folder,
                     source = excluded.source, rel_path = excluded.rel_path""",
                [(r["sha256"], now, now, folder, r["source"], r["rel_path"]) for r in rows],
            )
        return len(rows)
    finally:
        conn.close()


def export_info(path: str | Path, sha256: str) -> dict | None:
    conn = connect(path)
    try:
        r = conn.execute(
            "SELECT first_at, last_at, times, last_folder FROM exported WHERE sha256 = ?", (sha256,)
        ).fetchone()
        return dict(r) if r else None
    finally:
        conn.close()


def clear_exported(catalogue: sqlite3.Connection, path: str | Path, photo_ids: list[int] | None = None) -> int:
    """Forget the export history of these photos, or all of it. Returns how many rows."""
    conn = connect(path)
    try:
        with conn:
            if photo_ids is None:
                return conn.execute("DELETE FROM exported").rowcount
            shas = [(r["sha256"],) for r in _photos(catalogue, photo_ids)]
            return sum(conn.execute("DELETE FROM exported WHERE sha256 = ?", s).rowcount for s in shas)
    finally:
        conn.close()


# ---- custom tags --------------------------------------------------------------


class TagError(ValueError):
    """A custom tag request that cannot be done (duplicate or empty name, unknown tag)."""


def list_tags(path: str | Path) -> list[dict]:
    """Every custom tag with its examples' and negatives' content hashes, by name."""
    conn = connect(path)
    try:
        tags = [dict(r) for r in conn.execute("SELECT * FROM custom_tags ORDER BY name COLLATE NOCASE")]
        found: dict[str, dict[int, list[str]]] = {"examples": {}, "negatives": {}}
        for key, table in (("examples", "custom_tag_examples"), ("negatives", "custom_tag_negatives")):
            for r in conn.execute(f"SELECT tag_id, sha256 FROM {table} ORDER BY added_at, sha256"):
                found[key].setdefault(r["tag_id"], []).append(r["sha256"])
        for t in tags:
            t["examples"] = found["examples"].get(t["id"], [])
            t["negatives"] = found["negatives"].get(t["id"], [])
        return tags
    finally:
        conn.close()


def _clean_name(name: str) -> str:
    name = " ".join((name or "").split())
    if not name:
        raise TagError("the tag needs a name")
    return name


def _add_examples(
    conn: sqlite3.Connection, catalogue: sqlite3.Connection, tag_id: int, photo_ids: list[int], now: float, table: str = "custom_tag_examples"
) -> None:
    """Add photos as examples (or, with the negatives table, as negatives); a photo is
    only ever one of the two, so it leaves the other list."""
    rows = _photos(catalogue, photo_ids)
    other = "custom_tag_negatives" if table == "custom_tag_examples" else "custom_tag_examples"
    conn.executemany(f"DELETE FROM {other} WHERE tag_id = ? AND sha256 = ?", [(tag_id, r["sha256"]) for r in rows])
    conn.executemany(
        f"""INSERT INTO {table} (tag_id, sha256, source, rel_path, added_at) VALUES (?, ?, ?, ?, ?)
           ON CONFLICT (tag_id, sha256) DO UPDATE SET source = excluded.source, rel_path = excluded.rel_path""",
        [(tag_id, r["sha256"], r["source"], r["rel_path"], now) for r in rows],
    )


def create_tag(
    catalogue: sqlite3.Connection, path: str | Path, name: str, photo_ids: list[int], strictness: str = "normal",
    negatives: list[int] | None = None, cut: float | None = None,
) -> int:
    """A new tag from example photos (and photos that do not belong); returns its id."""
    name = _clean_name(name)
    if strictness not in STRICTNESS:
        raise TagError(f"strictness must be one of {', '.join(STRICTNESS)}")
    if not _photos(catalogue, photo_ids):
        raise TagError("choose at least one photo as an example")
    conn = connect(path)
    try:
        now = time.time()
        with conn:
            try:
                tag_id = conn.execute(
                    "INSERT INTO custom_tags (name, strictness, cut, created_at, updated_at) VALUES (?, ?, ?, ?, ?)",
                    (name, strictness, cut, now, now),
                ).lastrowid
            except sqlite3.IntegrityError:
                raise TagError(f'a tag named "{name}" already exists')
            if negatives:
                _add_examples(conn, catalogue, tag_id, negatives, now, "custom_tag_negatives")
            _add_examples(conn, catalogue, tag_id, photo_ids, now)  # (an example wins over a negative)
        return tag_id
    finally:
        conn.close()


def update_tag(
    catalogue: sqlite3.Connection,
    path: str | Path,
    tag_id: int,
    *,
    name: str | None = None,
    strictness: str | None = None,
    cut: float | None = None,
    add: list[int] | None = None,
    remove: list[int] | None = None,
    add_negatives: list[int] | None = None,
    remove_negatives: list[int] | None = None,
) -> None:
    """Rename, change strictness or the cut, add or remove example photos and negatives."""
    if strictness is not None and strictness not in STRICTNESS:
        raise TagError(f"strictness must be one of {', '.join(STRICTNESS)}")
    conn = connect(path)
    try:
        now = time.time()
        with conn:
            if conn.execute("SELECT 1 FROM custom_tags WHERE id = ?", (tag_id,)).fetchone() is None:
                raise TagError("no such tag")
            if name is not None:
                try:
                    conn.execute("UPDATE custom_tags SET name = ? WHERE id = ?", (_clean_name(name), tag_id))
                except sqlite3.IntegrityError:
                    raise TagError(f'a tag named "{_clean_name(name)}" already exists')
            if strictness is not None:
                conn.execute("UPDATE custom_tags SET strictness = ?, cut = NULL WHERE id = ?", (strictness, tag_id))
            if cut is not None:
                conn.execute("UPDATE custom_tags SET cut = ? WHERE id = ?", (float(cut), tag_id))
            if add:
                _add_examples(conn, catalogue, tag_id, add, now)
            if add_negatives:
                _add_examples(conn, catalogue, tag_id, add_negatives, now, "custom_tag_negatives")
            for table, ids in (("custom_tag_examples", remove), ("custom_tag_negatives", remove_negatives)):
                if ids:
                    conn.executemany(
                        f"DELETE FROM {table} WHERE tag_id = ? AND sha256 = ?",
                        [(tag_id, r["sha256"]) for r in _photos(catalogue, ids)],
                    )
            conn.execute("UPDATE custom_tags SET updated_at = ? WHERE id = ?", (now, tag_id))
    finally:
        conn.close()


def delete_tag(path: str | Path, tag_id: int) -> bool:
    conn = connect(path)
    try:
        with conn:
            conn.execute("DELETE FROM custom_tag_examples WHERE tag_id = ?", (tag_id,))
            conn.execute("DELETE FROM custom_tag_negatives WHERE tag_id = ?", (tag_id,))
            return conn.execute("DELETE FROM custom_tags WHERE id = ?", (tag_id,)).rowcount > 0
    finally:
        conn.close()


# ---- captions and fixed tags ----------------------------------------------------

GENERATE_MODES = ("add", "replace", "replace_all")
TAG_OPS = ("add", "remove", "rename")
TAG_POSITIONS = ("end", "start")  # where new tags go


def clean_tag(tag: str) -> str:
    """One tag as stored: trimmed, inner whitespace collapsed, no stray commas."""
    return " ".join((tag or "").split()).strip(" ,")


def clean_tags(tags) -> list[str]:
    """Cleaned tags in order, empty ones and repeats (ignoring case) left out."""
    out, seen = [], set()
    for t in tags or []:
        t = clean_tag(t)
        if t and t.casefold() not in seen:
            seen.add(t.casefold())
            out.append(t)
    return out


def _state(conn: sqlite3.Connection, shas: list[str]) -> dict[str, dict]:
    """{sha256: {caption, method, edited, tags: [(tag, method)], ocr}} for these photos;
    ocr is None (never read) or {text, translation, language, method, edited}."""
    out = {s: {"caption": None, "method": None, "edited": False, "tags": [], "ocr": None} for s in shas}
    for i in range(0, len(shas), 500):
        chunk = shas[i : i + 500]
        marks = ",".join("?" * len(chunk))
        for r in conn.execute(f"SELECT sha256, text, method, edited FROM captions WHERE sha256 IN ({marks})", chunk):
            out[r["sha256"]].update(caption=r["text"], method=r["method"], edited=bool(r["edited"]))
        for r in conn.execute(
            f"SELECT sha256, tag, method FROM fixed_tags WHERE sha256 IN ({marks}) ORDER BY position, added_at", chunk
        ):
            out[r["sha256"]]["tags"].append((r["tag"], r["method"]))
        for r in conn.execute(
            f"SELECT sha256, text, translation, language, method, edited FROM photo_text WHERE sha256 IN ({marks})", chunk
        ):
            out[r["sha256"]]["ocr"] = {
                "text": r["text"], "translation": r["translation"], "language": r["language"],
                "method": r["method"], "edited": bool(r["edited"]),
            }
    return out


def _public(st: dict) -> dict:
    ocr = st["ocr"] or {}
    return {
        "caption": st["caption"],
        "method": st["method"],
        "edited": st["edited"],
        "tags": [t for t, _ in st["tags"]],
        # text in the photo: None = never read, "" = read, none found
        "text": ocr.get("text"),
        "translation": ocr.get("translation", ""),
        "language": ocr.get("language"),
        "text_method": ocr.get("method"),
        "text_edited": ocr.get("edited", False),
    }


def captions_for(catalogue: sqlite3.Connection, path: str | Path, photo_ids: list[int]) -> dict[int, dict]:
    """{photo id: {caption, method, edited, tags}} (caption None and tags [] when there are none)."""
    rows = _photos(catalogue, photo_ids)
    conn = connect(path)
    try:
        st = _state(conn, sorted({r["sha256"] for r in rows}))
        return {r["id"]: _public(st[r["sha256"]]) for r in rows}
    finally:
        conn.close()


def _write(conn: sqlite3.Connection, r, caption=..., tags=..., *, method: str, edited: bool, now: float) -> None:
    """Replace a photo's caption and/or tags (``...`` leaves that part as it is).
    ``tags`` is [(tag, method)]; a caption of None or "" removes it."""
    if caption is not ...:
        if caption:
            conn.execute(
                """INSERT INTO captions (sha256, text, method, edited, source, rel_path, updated_at)
                   VALUES (?, ?, ?, ?, ?, ?, ?)
                   ON CONFLICT (sha256) DO UPDATE SET text = excluded.text, method = excluded.method,
                     edited = excluded.edited, source = excluded.source, rel_path = excluded.rel_path,
                     updated_at = excluded.updated_at""",
                (r["sha256"], caption, method, int(edited), r["source"], r["rel_path"], now),
            )
        else:
            conn.execute("DELETE FROM captions WHERE sha256 = ?", (r["sha256"],))
    if tags is not ...:
        conn.execute("DELETE FROM fixed_tags WHERE sha256 = ?", (r["sha256"],))
        conn.executemany(
            """INSERT OR IGNORE INTO fixed_tags (sha256, tag, position, method, source, rel_path, added_at)
               VALUES (?, ?, ?, ?, ?, ?, ?)""",
            [(r["sha256"], t, i, m, r["source"], r["rel_path"], now) for i, (t, m) in enumerate(tags)],
        )


def _write_text(conn: sqlite3.Connection, r, ocr: dict | None, *, method: str | None, edited: bool, now: float) -> None:
    """Replace a photo's read text ({text, translation, language}); None forgets it."""
    if ocr is None:
        conn.execute("DELETE FROM photo_text WHERE sha256 = ?", (r["sha256"],))
        return
    conn.execute(
        """INSERT INTO photo_text (sha256, text, translation, language, method, edited, source, rel_path, updated_at)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
           ON CONFLICT (sha256) DO UPDATE SET text = excluded.text, translation = excluded.translation,
             language = excluded.language, method = excluded.method, edited = excluded.edited,
             source = excluded.source, rel_path = excluded.rel_path, updated_at = excluded.updated_at""",
        (r["sha256"], (ocr.get("text") or "").strip(), (ocr.get("translation") or "").strip(), ocr.get("language") or None,
         method, int(edited), r["source"], r["rel_path"], now),
    )


def set_captions(catalogue: sqlite3.Connection, path: str | Path, items: list[dict]) -> dict[int, dict]:
    """Manual edits: ``[{id, caption?, tags?, text?, translation?}]``; a missing key
    leaves that part as it is (``text: None`` forgets the read text). Also used for
    undo, when an item may carry ``method``/``edited`` (and ``text_method``,
    ``text_edited``, ``language``) to restore.
    Returns the previous state of every changed photo (for undo)."""
    by_id = {it["id"]: it for it in items}
    rows = _photos(catalogue, list(by_id))
    conn = connect(path)
    try:
        before = _state(conn, sorted({r["sha256"] for r in rows}))
        now = time.time()
        with conn:
            for r in rows:
                it = by_id[r["id"]]
                method = it.get("method", "manual")
                edited = it.get("edited", method == "manual")
                caption = (it["caption"] or "").strip() if "caption" in it else ...
                tags = [(t, "manual") for t in clean_tags(it["tags"])] if "tags" in it else ...
                if tags is not ...:
                    old = {t.casefold(): m for t, m in before[r["sha256"]]["tags"]}
                    tags = [(t, old.get(t.casefold(), m)) for t, m in tags]  # keep where each came from
                _write(conn, r, caption, tags, method=method, edited=edited, now=now)
                if "text" in it or "translation" in it:
                    cur = before[r["sha256"]]["ocr"] or {}
                    if "text" in it and it["text"] is None:
                        ocr = None
                    else:
                        ocr = {
                            "text": it["text"] if "text" in it else cur.get("text", ""),
                            "translation": it["translation"] if "translation" in it else cur.get("translation", ""),
                            "language": it.get("language", cur.get("language")),
                        }
                    _write_text(
                        conn, r, ocr,
                        method=it.get("text_method", cur.get("method") or "manual"),
                        edited=it.get("text_edited", True),
                        now=now,
                    )
        return {r["id"]: _public(before[r["sha256"]]) | {"id": r["id"]} for r in rows}
    finally:
        conn.close()


def bulk_tags(
    catalogue: sqlite3.Connection, path: str | Path, photo_ids: list[int], op: str, tag: str, to: str | None = None,
    at: str = "end",
) -> dict[int, dict]:
    """Add a tag to all these photos (``at`` the start or the end of their tags),
    remove it from them, or rename it (renaming onto a tag a photo already has merges
    the two). Returns the previous state of the photos that changed (for undo)."""
    if at not in TAG_POSITIONS:
        raise ValueError(f"at must be one of {', '.join(TAG_POSITIONS)}")
    if op not in TAG_OPS:
        raise ValueError(f"op must be one of {', '.join(TAG_OPS)}")
    tag = clean_tag(tag)
    to = clean_tag(to or "")
    if not tag or (op == "rename" and not to):
        raise ValueError("the tag needs a name")
    rows = _photos(catalogue, photo_ids)
    conn = connect(path)
    try:
        before = _state(conn, sorted({r["sha256"] for r in rows}))
        changed = {}
        now = time.time()
        with conn:
            for r in rows:
                tags = before[r["sha256"]]["tags"]
                keys = [t.casefold() for t, _ in tags]
                if op == "add":
                    if tag.casefold() in keys:
                        continue
                    new = [(tag, "manual"), *tags] if at == "start" else [*tags, (tag, "manual")]
                elif tag.casefold() not in keys:
                    continue
                elif op == "remove":
                    new = [(t, m) for t, m in tags if t.casefold() != tag.casefold()]
                else:  # rename, in place; a copy of the new name further on is dropped
                    new, seen = [], set()
                    for t, m in tags:
                        if t.casefold() == tag.casefold():
                            t = to
                        if t.casefold() not in seen:
                            seen.add(t.casefold())
                            new.append((t, m))
                _write(conn, r, ..., new, method="manual", edited=False, now=now)
                changed[r["id"]] = _public(before[r["sha256"]]) | {"id": r["id"]}
        return changed
    finally:
        conn.close()


def store_generated(
    catalogue: sqlite3.Connection, path: str | Path, results: dict[int, dict], method: str, mode: str = "add",
    *, at: str = "end", limit: tuple[str, int] | None = None, count_tokens=None,
) -> int:
    """Store generated ``{photo id: {caption?, tags?, text?, translation_only?}}``.
    Modes:
    add: a caption only where there is none, tags appended (repeats skipped), text
    only for photos never read;
    replace: generated captions, tags and text replaced, typed or edited ones kept;
    replace_all: everything replaced.
    ``text`` is {text, translation, language} ("" text: read, none found);
    ``translation_only`` (translating the current text again) always replaces the
    translation of text that was read.
    New tags go ``at`` the start or the end of the tags kept. ``limit`` ("tokens" |
    "tags", n) stops adding new tags once the whole list would exceed n (tokens as
    counted by ``count_tokens`` on the comma-separated list); kept tags always stay.
    Returns how many photos changed."""
    if mode not in GENERATE_MODES:
        raise ValueError(f"mode must be one of {', '.join(GENERATE_MODES)}")
    if at not in TAG_POSITIONS:
        raise ValueError(f"at must be one of {', '.join(TAG_POSITIONS)}")

    def size(tags: list[tuple[str, str]]) -> int:
        if limit[0] == "tags":
            return len(tags)
        return count_tokens(", ".join(t for t, _ in tags))

    rows = _photos(catalogue, list(results))
    conn = connect(path)
    try:
        before = _state(conn, sorted({r["sha256"] for r in rows}))
        now = time.time()
        n = 0
        with conn:
            for r in rows:
                res, st = results[r["id"]], before[r["sha256"]]
                caption = tags = ...
                new_caption = (res.get("caption") or "").strip()
                if new_caption:
                    keep = st["caption"] and (mode == "add" or (mode == "replace" and (st["edited"] or st["method"] == "manual")))
                    if not keep:
                        caption = new_caption
                if res.get("tags"):
                    if mode == "add":
                        kept = st["tags"]
                    elif mode == "replace":
                        kept = [(t, m) for t, m in st["tags"] if m == "manual"]
                    else:
                        kept = []
                    seen = {t.casefold() for t, _ in kept}
                    new: list[tuple[str, str]] = []
                    for t in clean_tags(res["tags"]):
                        if t.casefold() not in seen:
                            candidate = [*new, (t, method)]
                            whole = [*candidate, *kept] if at == "start" else [*kept, *candidate]
                            if limit and size(whole) > limit[1]:
                                break  # in the model's order: the least certain go
                            seen.add(t.casefold())
                            new = candidate
                    tags = [*new, *kept] if at == "start" else [*kept, *new]
                    if tags == st["tags"]:
                        tags = ...
                ocr = ...
                if isinstance(res.get("text"), dict):
                    old = st["ocr"]
                    # A photo only skipped by the quick text check ("clip") was never read.
                    guessed = old is not None and old["method"] == "clip" and method != "clip"
                    keep = old is not None and not guessed and (mode == "add" or (mode == "replace" and old["edited"]))
                    if not keep:
                        ocr = res["text"]
                elif "translation_only" in res and st["ocr"] is not None:
                    ocr = {**st["ocr"], "translation": res["translation_only"] or ""}
                    if ocr == st["ocr"]:
                        ocr = ...
                if caption is ... and tags is ... and ocr is ...:
                    continue
                _write(conn, r, caption, tags, method=method, edited=False, now=now)
                if ocr is not ...:
                    edited = st["ocr"]["edited"] if "translation_only" in res and st["ocr"] else False
                    text_method = st["ocr"]["method"] if "translation_only" in res and st["ocr"] else method
                    _write_text(conn, r, ocr, method=text_method, edited=edited, now=now)
                n += 1
        return n
    finally:
        conn.close()
